from sqlalchemy.orm import Session

from ..auth import get_password_hash
from ..core.config import settings
from ..models import User, Book


def seed(db: Session) -> None:
    # Seed admin
    admin = db.query(User).filter(User.email == settings.admin_email).first()
    if not admin:
        admin = User(
            name="Admin",
            email=settings.admin_email,
            hashed_password=get_password_hash(settings.admin_password),
            is_admin=True,
        )
        db.add(admin)
        db.commit()

    # Seed demo user
    demo_email = "demo@student.com"
    demo = db.query(User).filter(User.email == demo_email).first()
    if not demo:
        demo = User(
            name="Demo Student",
            email=demo_email,
            hashed_password=get_password_hash("password123"),
            college="Sample College",
            contact_no="+1-555-0100",
        )
        db.add(demo)
        db.commit()
        db.refresh(demo)

    # Seed books if none
    count = db.query(Book).count()
    if count == 0:
        samples = [
            # Fiction Books
            Book(
                title="The Alchemist",
                author="Paulo Coelho",
                category="Fiction",
                price=250,
                description="A magical story about following your dreams and finding your destiny.",
                image_url="https://covers.openlibrary.org/b/isbn/9780062315007-L.jpg",
                seller_id=demo.id,
            ),
            Book(
                title="1984",
                author="George Orwell",
                category="Fiction",
                price=220,
                description="A dystopian social science fiction novel and cautionary tale.",
                image_url="https://covers.openlibrary.org/b/isbn/9780451524935-L.jpg",
                seller_id=demo.id,
            ),
            Book(
                title="To Kill a Mockingbird",
                author="Harper Lee",
                category="Fiction",
                price=280,
                description="A gripping tale of racial injustice and childhood innocence in the American South.",
                image_url="https://covers.openlibrary.org/b/isbn/9780061120084-L.jpg",
                seller_id=demo.id,
            ),
            Book(
                title="Harry Potter and the Sorcerer's Stone",
                author="J.K. Rowling",
                category="Fiction",
                price=350,
                description="The magical journey begins at Hogwarts School of Witchcraft and Wizardry.",
                image_url="https://covers.openlibrary.org/b/isbn/9780590353427-L.jpg",
                seller_id=demo.id,
            ),
            Book(
                title="Pride and Prejudice",
                author="Jane Austen",
                category="Fiction",
                price=240,
                description="A romantic novel of manners set in Georgian England.",
                image_url="https://covers.openlibrary.org/b/isbn/9780141439518-L.jpg",
                seller_id=demo.id,
            ),
            Book(
                title="The Great Gatsby",
                author="F. Scott Fitzgerald",
                category="Fiction",
                price=220,
                description="The story of the mysteriously wealthy Jay Gatsby and his love for Daisy Buchanan.",
                image_url="https://covers.openlibrary.org/b/isbn/9780743273565-L.jpg",
                seller_id=demo.id,
            ),
            Book(
                title="The Catcher in the Rye",
                author="J.D. Salinger",
                category="Fiction",
                price=260,
                description="The experiences of a teenager in New York City after being expelled from prep school.",
                image_url="https://covers.openlibrary.org/b/isbn/9780316769488-L.jpg",
                seller_id=demo.id,
            ),
            Book(
                title="The Hobbit",
                author="J.R.R. Tolkien",
                category="Fiction",
                price=320,
                description="A fantasy adventure about a hobbit who embarks on an unexpected journey.",
                image_url="https://covers.openlibrary.org/b/isbn/9780547928227-L.jpg",
                seller_id=demo.id,
            ),
            Book(
                title="Animal Farm",
                author="George Orwell",
                category="Fiction",
                price=200,
                description="A satirical allegory of totalitarianism where farm animals rebel against humans.",
                image_url="https://covers.openlibrary.org/b/isbn/9780452284244-L.jpg",
                seller_id=demo.id,
            ),
            Book(
                title="The Fellowship of the Ring",
                author="J.R.R. Tolkien",
                category="Fiction",
                price=600,
                description="The first part of the Lord of the Rings trilogy about the quest to destroy the One Ring.",
                image_url="https://covers.openlibrary.org/b/isbn/9780544003415-L.jpg",
                seller_id=demo.id,
            ),
            Book(
                title="The Kite Runner",
                author="Khaled Hosseini",
                category="Fiction",
                price=310,
                description="A powerful story of friendship, redemption, and the devastating effects of war.",
                image_url="https://covers.openlibrary.org/b/isbn/9781594631931-L.jpg",
                seller_id=demo.id,
            ),
            Book(
                title="Life of Pi",
                author="Yann Martel",
                category="Fiction",
                price=290,
                description="A young man's survival story after a shipwreck leaves him stranded on a lifeboat with a tiger.",
                image_url="https://covers.openlibrary.org/b/isbn/9780156027328-L.jpg",
                seller_id=demo.id,
            ),
            
            # Self-Help Books
            Book(
                title="Atomic Habits",
                author="James Clear",
                category="Self-Help",
                price=400,
                description="An easy and proven way to build good habits and break bad ones.",
                image_url="https://covers.openlibrary.org/b/isbn/9780735211292-L.jpg",
                seller_id=demo.id,
            ),
            Book(
                title="The Subtle Art of Not Giving a F*ck",
                author="Mark Manson",
                category="Self-Help",
                price=320,
                description="A counterintuitive approach to living a good life.",
                image_url="https://covers.openlibrary.org/b/isbn/9780062457714-L.jpg",
                seller_id=demo.id,
            ),
            Book(
                title="The 7 Habits of Highly Effective People",
                author="Stephen Covey",
                category="Self-Help",
                price=360,
                description="Powerful lessons in personal change and effectiveness.",
                image_url="https://covers.openlibrary.org/b/isbn/9781982137274-L.jpg",
                seller_id=demo.id,
            ),
            Book(
                title="How to Win Friends and Influence People",
                author="Dale Carnegie",
                category="Self-Help",
                price=280,
                description="Timeless advice on building relationships and influencing others.",
                image_url="https://covers.openlibrary.org/b/isbn/9780671027032-L.jpg",
                seller_id=demo.id,
            ),
            Book(
                title="The Power of Now",
                author="Eckhart Tolle",
                category="Self-Help",
                price=340,
                description="A guide to spiritual enlightenment and living in the present moment.",
                image_url="https://covers.openlibrary.org/b/isbn/9781577314806-L.jpg",
                seller_id=demo.id,
            ),
            Book(
                title="You Can Win",
                author="Shiv Khera",
                category="Self-Help",
                price=250,
                description="A step-by-step guide to achieve success and lead a fulfilling life.",
                image_url="https://covers.openlibrary.org/b/isbn/9780230638426-L.jpg",
                seller_id=demo.id,
            ),
            Book(
                title="Man's Search for Meaning",
                author="Viktor E. Frankl",
                category="Self-Help",
                price=260,
                description="A psychiatrist's memoir of survival in Nazi death camps and lessons about human resilience.",
                image_url="https://covers.openlibrary.org/b/isbn/9780807014295-L.jpg",
                seller_id=demo.id,
            ),
            
            # Business Books
            Book(
                title="Rich Dad Poor Dad",
                author="Robert Kiyosaki",
                category="Business",
                price=300,
                description="What the rich teach their kids about money that the poor and middle class do not.",
                image_url="https://covers.openlibrary.org/b/isbn/9781612680194-L.jpg",
                seller_id=demo.id,
            ),
            Book(
                title="The Psychology of Money",
                author="Morgan Housel",
                category="Business",
                price=380,
                description="Timeless lessons on wealth, greed, and happiness.",
                image_url="https://covers.openlibrary.org/b/isbn/9780857197689-L.jpg",
                seller_id=demo.id,
            ),
            Book(
                title="The Lean Startup",
                author="Eric Ries",
                category="Business",
                price=380,
                description="How today's entrepreneurs use continuous innovation to create radically successful businesses.",
                image_url="https://covers.openlibrary.org/b/isbn/9780307887894-L.jpg",
                seller_id=demo.id,
            ),
            Book(
                title="Zero to One",
                author="Peter Thiel",
                category="Business",
                price=350,
                description="Notes on startups, or how to build the future.",
                image_url="https://covers.openlibrary.org/b/isbn/9780804139298-L.jpg",
                seller_id=demo.id,
            ),
            Book(
                title="Good to Great",
                author="Jim Collins",
                category="Business",
                price=420,
                description="Why some companies make the leap and others don't.",
                image_url="https://covers.openlibrary.org/b/isbn/9780066620992-L.jpg",
                seller_id=demo.id,
            ),
            Book(
                title="The Intelligent Investor",
                author="Benjamin Graham",
                category="Business",
                price=450,
                description="The definitive book on value investing, a must-read for serious investors.",
                image_url="https://covers.openlibrary.org/b/isbn/9780060555665-L.jpg",
                seller_id=demo.id,
            ),
            Book(
                title="Think and Grow Rich",
                author="Napoleon Hill",
                category="Business",
                price=280,
                description="The classic guide to achieving wealth and success.",
                image_url="https://covers.openlibrary.org/b/isbn/9781585424337-L.jpg",
                seller_id=demo.id,
            ),
            Book(
                title="The 4-Hour Workweek",
                author="Timothy Ferriss",
                category="Business",
                price=360,
                description="Escape 9-5, live anywhere, and join the new rich.",
                image_url="https://covers.openlibrary.org/b/isbn/9780307465351-L.jpg",
                seller_id=demo.id,
            ),
            
            # Programming & Technology
            Book(
                title="Clean Code",
                author="Robert C. Martin",
                category="Programming",
                price=450,
                description="A handbook of agile software craftsmanship. Learn to write clean, maintainable code.",
                image_url="https://covers.openlibrary.org/b/isbn/9780132350884-L.jpg",
                seller_id=demo.id,
            ),
            Book(
                title="Introduction to Algorithms",
                author="Thomas H. Cormen",
                category="Computer Science",
                price=850,
                description="Comprehensive algorithms textbook. The definitive guide to algorithms.",
                image_url="https://covers.openlibrary.org/b/isbn/9780262033848-L.jpg",
                seller_id=demo.id,
            ),
            Book(
                title="The Pragmatic Programmer",
                author="Andrew Hunt, David Thomas",
                category="Programming",
                price=480,
                description="Your journey to mastery in software craftsmanship.",
                image_url="https://covers.openlibrary.org/b/isbn/9780135957059-L.jpg",
                seller_id=demo.id,
            ),
            Book(
                title="Design Patterns",
                author="Erich Gamma",
                category="Programming",
                price=550,
                description="Elements of reusable object-oriented software.",
                image_url="https://covers.openlibrary.org/b/isbn/9780201633610-L.jpg",
                seller_id=demo.id,
            ),
            Book(
                title="Eloquent JavaScript",
                author="Marijn Haverbeke",
                category="Programming",
                price=420,
                description="A modern introduction to programming with JavaScript.",
                image_url="https://covers.openlibrary.org/b/isbn/9781593279509-L.jpg",
                seller_id=demo.id,
            ),
            Book(
                title="Cracking the Coding Interview",
                author="Gayle Laakmann McDowell",
                category="Programming",
                price=520,
                description="189 programming questions and solutions for tech interviews.",
                image_url="https://covers.openlibrary.org/b/isbn/9780984782857-L.jpg",
                seller_id=demo.id,
            ),
            
            # Science & History
            Book(
                title="Sapiens: A Brief History of Humankind",
                author="Yuval Noah Harari",
                category="History",
                price=350,
                description="A brief history of humankind. From the Stone Age to the modern era.",
                image_url="https://covers.openlibrary.org/b/isbn/9780062316097-L.jpg",
                seller_id=demo.id,
            ),
            Book(
                title="Thinking, Fast and Slow",
                author="Daniel Kahneman",
                category="Science",
                price=420,
                description="Explores the two systems that drive the way we think and make decisions.",
                image_url="https://covers.openlibrary.org/b/isbn/9780374533557-L.jpg",
                seller_id=demo.id,
            ),
            Book(
                title="A Brief History of Time",
                author="Stephen Hawking",
                category="Science",
                price=320,
                description="From the Big Bang to black holes, a landmark book on cosmology.",
                image_url="https://covers.openlibrary.org/b/isbn/9780553380163-L.jpg",
                seller_id=demo.id,
            ),
            Book(
                title="Educated",
                author="Tara Westover",
                category="Biography",
                price=360,
                description="A memoir about a young woman who leaves her survivalist family and goes on to earn a PhD.",
                image_url="https://covers.openlibrary.org/b/isbn/9780399590504-L.jpg",
                seller_id=demo.id,
            ),
            Book(
                title="The Immortal Life of Henrietta Lacks",
                author="Rebecca Skloot",
                category="Science",
                price=340,
                description="The story of a woman whose cells revolutionized medical research.",
                image_url="https://covers.openlibrary.org/b/isbn/9781400052172-L.jpg",
                seller_id=demo.id,
            ),
            Book(
                title="Guns, Germs, and Steel",
                author="Jared Diamond",
                category="History",
                price=390,
                description="The fates of human societies and why some civilizations succeeded.",
                image_url="https://covers.openlibrary.org/b/isbn/9780393317558-L.jpg",
                seller_id=demo.id,
            ),
            
            # Thriller & Mystery
            Book(
                title="The Da Vinci Code",
                author="Dan Brown",
                category="Thriller",
                price=290,
                description="A murder in the Louvre leads to a sinister plot to uncover a secret.",
                image_url="https://covers.openlibrary.org/b/isbn/9780307474278-L.jpg",
                seller_id=demo.id,
            ),
            Book(
                title="Gone Girl",
                author="Gillian Flynn",
                category="Thriller",
                price=310,
                description="A psychological thriller about a woman who goes missing on her anniversary.",
                image_url="https://covers.openlibrary.org/b/isbn/9780307588371-L.jpg",
                seller_id=demo.id,
            ),
            Book(
                title="The Girl with the Dragon Tattoo",
                author="Stieg Larsson",
                category="Thriller",
                price=330,
                description="A journalist and a hacker investigate a decades-old disappearance.",
                image_url="https://covers.openlibrary.org/b/isbn/9780307454546-L.jpg",
                seller_id=demo.id,
            ),
            Book(
                title="The Silent Patient",
                author="Alex Michaelides",
                category="Thriller",
                price=300,
                description="A woman shoots her husband and then never speaks another word.",
                image_url="https://covers.openlibrary.org/b/isbn/9781250301697-L.jpg",
                seller_id=demo.id,
            ),
            
            # Romance
            Book(
                title="The Notebook",
                author="Nicholas Sparks",
                category="Romance",
                price=240,
                description="An enduring love story that spans decades.",
                image_url="https://covers.openlibrary.org/b/isbn/9780446676090-L.jpg",
                seller_id=demo.id,
            ),
            Book(
                title="Me Before You",
                author="Jojo Moyes",
                category="Romance",
                price=260,
                description="A heartbreaking love story about a caregiver and her quadriplegic patient.",
                image_url="https://covers.openlibrary.org/b/isbn/9780143124542-L.jpg",
                seller_id=demo.id,
            ),
            Book(
                title="The Fault in Our Stars",
                author="John Green",
                category="Romance",
                price=270,
                description="Two teens with cancer fall in love in this heartrending novel.",
                image_url="https://covers.openlibrary.org/b/isbn/9780525478812-L.jpg",
                seller_id=demo.id,
            ),
            
            # Children's Books
            Book(
                title="Charlotte's Web",
                author="E.B. White",
                category="Children",
                price=220,
                description="The classic story of a pig and a spider's beautiful friendship.",
                image_url="https://covers.openlibrary.org/b/isbn/9780064400558-L.jpg",
                seller_id=demo.id,
            ),
            Book(
                title="Matilda",
                author="Roald Dahl",
                category="Children",
                price=230,
                description="A brilliant young girl with telekinetic powers stands up to tyranny.",
                image_url="https://covers.openlibrary.org/b/isbn/9780142410370-L.jpg",
                seller_id=demo.id,
            ),
            Book(
                title="The Very Hungry Caterpillar",
                author="Eric Carle",
                category="Children",
                price=200,
                description="A beloved children's book about a caterpillar's transformation into a butterfly.",
                image_url="https://covers.openlibrary.org/b/isbn/9780399226908-L.jpg",
                seller_id=demo.id,
            ),
            
            # Poetry & Philosophy
            Book(
                title="The Prophet",
                author="Kahlil Gibran",
                category="Poetry",
                price=210,
                description="A collection of poetic essays on love, joy, sorrow, and the human condition.",
                image_url="https://covers.openlibrary.org/b/isbn/9780394404288-L.jpg",
                seller_id=demo.id,
            ),
            Book(
                title="Meditations",
                author="Marcus Aurelius",
                category="Religion",
                price=250,
                description="The personal writings of the Roman Emperor on Stoic philosophy.",
                image_url="https://covers.openlibrary.org/b/isbn/9780812968255-L.jpg",
                seller_id=demo.id,
            ),
            Book(
                title="The Art of War",
                author="Sun Tzu",
                category="History",
                price=230,
                description="An ancient Chinese military treatise on strategy and tactics.",
                image_url="https://covers.openlibrary.org/b/isbn/9781599869773-L.jpg",
                seller_id=demo.id,
            ),
        ]
        db.add_all(samples)
        db.commit()

